scale max 880 width
skinparam sequenceMessageAlign center
skinparam shadowing false
skinparam roundcorner 10
skinparam padding 10
skinparam defaultFontSize 12
skinparam defaultFontName "Noto Sans CJK KR"

skinparam note {
  BackgroundColor #9EA0CA
  BorderColor #ffffff
  FontColor #ffffff
  FontSize 14
  FontStyle bold
}

skinparam sequence {
  ArrowColor #000000
  ActorBorderColor #000000
  ActorFontStyle Bolder


  LifeLineBorderColor #000000
  LifeLineBackgroundColor transparent
  ParticipantBorderColor transparent
  ParticipantFontSize 14
  ParticipantFontColor #ffffff
  ParticipantFontStyle bold

  BoxBorderColor #000000
  BoxFontColor #ffffff
    BoxFontSize 14
    BoxFontStyle bold
}
hide footbox

skinparam activity {
  BackgroundColor #9EA0CA
  BarColor #ffffff
  BorderColor #ffffff
  DiamondBackgroundColor #05D686
  DiamondBorderColor #ffffff
  DiamondFontColor #ffffff
  DiamondFontSize 14
  DiamondFontStyle bold
  FontColor #ffffff 
  FontSize 14
  FontStyle bold
}